"""Modifications

Revision ID: 407693954288
Revises: 557636fad666
Create Date: 2025-07-17 18:06:40.113795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '407693954288'
down_revision = '557636fad666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.LargeBinary(), nullable=True),
    sa.Column('github_username', sa.String(length=64), nullable=False),
    sa.Column('resume_uploaded', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_username')
    )
    op.create_table('repository',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('languages', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('commit_summary', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('access_token', sa.BLOB(), nullable=True),
    sa.Column('github_username', sa.VARCHAR(length=64), nullable=False),
    sa.Column('resume_uploaded', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_username')
    )
    op.drop_table('repository')
    op.drop_table('user')
    # ### end Alembic commands ###
