"""Changed languages and commit_summary columns to be lists by default

Revision ID: 502fb5a99ce2
Revises: 407693954288
Create Date: 2025-07-18 14:27:24.605997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '502fb5a99ce2'
down_revision = '407693954288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repository', schema=None) as batch_op:
        batch_op.alter_column('languages',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repository', schema=None) as batch_op:
        batch_op.alter_column('languages',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
