"""Added user model

Revision ID: 557636fad666
Revises: 
Create Date: 2025-07-17 14:18:21.138683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '557636fad666'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('access_token', sa.LargeBinary(), nullable=True),
    sa.Column('github_username', sa.String(length=64), nullable=False),
    sa.Column('resume_uploaded', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
